FROM arm32v6/golang:1.9-alpine as builder

COPY . /go/src/mumble.info/grumble

WORKDIR /go/src/mumble.info/grumble

RUN apk add --no-cache git \
  && go get -v -t ./... \
  && go build mumble.info/grumble/cmd/grumble \
  && go test -v ./...

FROM arm32v6/golang:1.9-alpine

COPY --from=builder /go/bin /go/bin

ENV DATADIR /data

RUN mkdir /data

WORKDIR /data

VOLUME /data

ENTRYPOINT [ "/go/bin/grumble", "--datadir", "/data", "--log", "/data/grumble.log" ]
