include $(GOROOT)/src/Make.inc

TARG = grumble/freezer
GOFILES = \
	writer.go \
	walker.go \
	types.go \
	types.pb.go \
	error.go

include $(GOROOT)/src/Make.pkg
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf

