// Code generated by protoc-gen-go from "types.proto"
// DO NOT EDIT!

package freezer

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto & math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Server struct {
	Config           []*ConfigKeyValuePair `protobuf:"bytes,2,rep,name=config" json:"config,omitempty"`
	BanList          *BanList              `protobuf:"bytes,3,opt,name=ban_list" json:"ban_list,omitempty"`
	Channels         []*Channel            `protobuf:"bytes,4,rep,name=channels" json:"channels,omitempty"`
	Users            []*User               `protobuf:"bytes,5,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte                `json:",omitempty"`
}

func (this *Server) Reset()         { *this = Server{} }
func (this *Server) String() string { return proto.CompactTextString(this) }

type ConfigKeyValuePair struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ConfigKeyValuePair) Reset()         { *this = ConfigKeyValuePair{} }
func (this *ConfigKeyValuePair) String() string { return proto.CompactTextString(this) }

type Ban struct {
	Ip               []byte  `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask             *uint32 `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	Username         *string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	CertHash         *string `protobuf:"bytes,4,opt,name=cert_hash" json:"cert_hash,omitempty"`
	Reason           *string `protobuf:"bytes,5,opt,name=reason" json:"reason,omitempty"`
	Start            *int64  `protobuf:"varint,6,opt,name=start" json:"start,omitempty"`
	Duration         *uint32 `protobuf:"varint,7,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Ban) Reset()         { *this = Ban{} }
func (this *Ban) String() string { return proto.CompactTextString(this) }

type BanList struct {
	Bans             []*Ban `protobuf:"bytes,1,rep,name=bans" json:"bans,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *BanList) Reset()         { *this = BanList{} }
func (this *BanList) String() string { return proto.CompactTextString(this) }

type User struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	CertHash         *string `protobuf:"bytes,4,opt,name=cert_hash" json:"cert_hash,omitempty"`
	Email            *string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	TextureBlob      *string `protobuf:"bytes,6,opt,name=texture_blob" json:"texture_blob,omitempty"`
	CommentBlob      *string `protobuf:"bytes,7,opt,name=comment_blob" json:"comment_blob,omitempty"`
	LastChannelId    *uint32 `protobuf:"varint,8,opt,name=last_channel_id" json:"last_channel_id,omitempty"`
	LastActive       *uint64 `protobuf:"varint,9,opt,name=last_active" json:"last_active,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }

type UserRemove struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserRemove) Reset()         { *this = UserRemove{} }
func (this *UserRemove) String() string { return proto.CompactTextString(this) }

type Channel struct {
	Id               *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ParentId         *uint32  `protobuf:"varint,3,opt,name=parent_id" json:"parent_id,omitempty"`
	Position         *int64   `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	InheritAcl       *bool    `protobuf:"varint,5,opt,name=inherit_acl" json:"inherit_acl,omitempty"`
	Links            []uint32 `protobuf:"varint,6,rep,name=links" json:"links,omitempty"`
	Acl              []*ACL   `protobuf:"bytes,7,rep,name=acl" json:"acl,omitempty"`
	Groups           []*Group `protobuf:"bytes,8,rep,name=groups" json:"groups,omitempty"`
	DescriptionBlob  *string  `protobuf:"bytes,9,opt,name=description_blob" json:"description_blob,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Channel) Reset()         { *this = Channel{} }
func (this *Channel) String() string { return proto.CompactTextString(this) }

type ChannelRemove struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChannelRemove) Reset()         { *this = ChannelRemove{} }
func (this *ChannelRemove) String() string { return proto.CompactTextString(this) }

type ACL struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Group            *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	ApplyHere        *bool   `protobuf:"varint,3,opt,name=apply_here" json:"apply_here,omitempty"`
	ApplySubs        *bool   `protobuf:"varint,4,opt,name=apply_subs" json:"apply_subs,omitempty"`
	Allow            *uint32 `protobuf:"varint,5,opt,name=allow" json:"allow,omitempty"`
	Deny             *uint32 `protobuf:"varint,6,opt,name=deny" json:"deny,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ACL) Reset()         { *this = ACL{} }
func (this *ACL) String() string { return proto.CompactTextString(this) }

type Group struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Inherit          *bool    `protobuf:"varint,2,opt,name=inherit" json:"inherit,omitempty"`
	Inheritable      *bool    `protobuf:"varint,3,opt,name=inheritable" json:"inheritable,omitempty"`
	Add              []uint32 `protobuf:"varint,4,rep,name=add" json:"add,omitempty"`
	Remove           []uint32 `protobuf:"varint,5,rep,name=remove" json:"remove,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Group) Reset()         { *this = Group{} }
func (this *Group) String() string { return proto.CompactTextString(this) }

func init() {
}
