// Code generated by protoc-gen-go from "Mumble.proto"
// DO NOT EDIT!

package mumbleproto

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto & math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type Reject_RejectType int32

const (
	Reject_None            Reject_RejectType = 0
	Reject_WrongVersion    Reject_RejectType = 1
	Reject_InvalidUsername Reject_RejectType = 2
	Reject_WrongUserPW     Reject_RejectType = 3
	Reject_WrongServerPW   Reject_RejectType = 4
	Reject_UsernameInUse   Reject_RejectType = 5
	Reject_ServerFull      Reject_RejectType = 6
	Reject_NoCertificate   Reject_RejectType = 7
)

var Reject_RejectType_name = map[int32]string{
	0: "None",
	1: "WrongVersion",
	2: "InvalidUsername",
	3: "WrongUserPW",
	4: "WrongServerPW",
	5: "UsernameInUse",
	6: "ServerFull",
	7: "NoCertificate",
}
var Reject_RejectType_value = map[string]int32{
	"None":            0,
	"WrongVersion":    1,
	"InvalidUsername": 2,
	"WrongUserPW":     3,
	"WrongServerPW":   4,
	"UsernameInUse":   5,
	"ServerFull":      6,
	"NoCertificate":   7,
}

func NewReject_RejectType(x Reject_RejectType) *Reject_RejectType {
	e := Reject_RejectType(x)
	return &e
}
func (x Reject_RejectType) String() string {
	return proto.EnumName(Reject_RejectType_name, int32(x))
}

type PermissionDenied_DenyType int32

const (
	PermissionDenied_Text               PermissionDenied_DenyType = 0
	PermissionDenied_Permission         PermissionDenied_DenyType = 1
	PermissionDenied_SuperUser          PermissionDenied_DenyType = 2
	PermissionDenied_ChannelName        PermissionDenied_DenyType = 3
	PermissionDenied_TextTooLong        PermissionDenied_DenyType = 4
	PermissionDenied_H9K                PermissionDenied_DenyType = 5
	PermissionDenied_TemporaryChannel   PermissionDenied_DenyType = 6
	PermissionDenied_MissingCertificate PermissionDenied_DenyType = 7
	PermissionDenied_UserName           PermissionDenied_DenyType = 8
	PermissionDenied_ChannelFull        PermissionDenied_DenyType = 9
)

var PermissionDenied_DenyType_name = map[int32]string{
	0: "Text",
	1: "Permission",
	2: "SuperUser",
	3: "ChannelName",
	4: "TextTooLong",
	5: "H9K",
	6: "TemporaryChannel",
	7: "MissingCertificate",
	8: "UserName",
	9: "ChannelFull",
}
var PermissionDenied_DenyType_value = map[string]int32{
	"Text":               0,
	"Permission":         1,
	"SuperUser":          2,
	"ChannelName":        3,
	"TextTooLong":        4,
	"H9K":                5,
	"TemporaryChannel":   6,
	"MissingCertificate": 7,
	"UserName":           8,
	"ChannelFull":        9,
}

func NewPermissionDenied_DenyType(x PermissionDenied_DenyType) *PermissionDenied_DenyType {
	e := PermissionDenied_DenyType(x)
	return &e
}
func (x PermissionDenied_DenyType) String() string {
	return proto.EnumName(PermissionDenied_DenyType_name, int32(x))
}

type ContextActionModify_Context int32

const (
	ContextActionModify_Server  ContextActionModify_Context = 1
	ContextActionModify_Channel ContextActionModify_Context = 2
	ContextActionModify_User    ContextActionModify_Context = 4
)

var ContextActionModify_Context_name = map[int32]string{
	1: "Server",
	2: "Channel",
	4: "User",
}
var ContextActionModify_Context_value = map[string]int32{
	"Server":  1,
	"Channel": 2,
	"User":    4,
}

func NewContextActionModify_Context(x ContextActionModify_Context) *ContextActionModify_Context {
	e := ContextActionModify_Context(x)
	return &e
}
func (x ContextActionModify_Context) String() string {
	return proto.EnumName(ContextActionModify_Context_name, int32(x))
}

type ContextActionModify_Operation int32

const (
	ContextActionModify_Add    ContextActionModify_Operation = 0
	ContextActionModify_Remove ContextActionModify_Operation = 1
)

var ContextActionModify_Operation_name = map[int32]string{
	0: "Add",
	1: "Remove",
}
var ContextActionModify_Operation_value = map[string]int32{
	"Add":    0,
	"Remove": 1,
}

func NewContextActionModify_Operation(x ContextActionModify_Operation) *ContextActionModify_Operation {
	e := ContextActionModify_Operation(x)
	return &e
}
func (x ContextActionModify_Operation) String() string {
	return proto.EnumName(ContextActionModify_Operation_name, int32(x))
}

type Version struct {
	Version          *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Release          *string `protobuf:"bytes,2,opt,name=release" json:"release,omitempty"`
	Os               *string `protobuf:"bytes,3,opt,name=os" json:"os,omitempty"`
	OsVersion        *string `protobuf:"bytes,4,opt,name=os_version" json:"os_version,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Version) Reset()         { *this = Version{} }
func (this *Version) String() string { return proto.CompactTextString(this) }

type UDPTunnel struct {
	Packet           []byte `protobuf:"bytes,1,req,name=packet" json:"packet,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *UDPTunnel) Reset()         { *this = UDPTunnel{} }
func (this *UDPTunnel) String() string { return proto.CompactTextString(this) }

type Authenticate struct {
	Username         *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password         *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Tokens           []string `protobuf:"bytes,3,rep,name=tokens" json:"tokens,omitempty"`
	CeltVersions     []int32  `protobuf:"varint,4,rep,name=celt_versions" json:"celt_versions,omitempty"`
	Opus             *bool    `protobuf:"varint,5,opt,name=opus,def=0" json:"opus,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Authenticate) Reset()         { *this = Authenticate{} }
func (this *Authenticate) String() string { return proto.CompactTextString(this) }

const Default_Authenticate_Opus bool = false

type Ping struct {
	Timestamp        *uint64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Good             *uint32  `protobuf:"varint,2,opt,name=good" json:"good,omitempty"`
	Late             *uint32  `protobuf:"varint,3,opt,name=late" json:"late,omitempty"`
	Lost             *uint32  `protobuf:"varint,4,opt,name=lost" json:"lost,omitempty"`
	Resync           *uint32  `protobuf:"varint,5,opt,name=resync" json:"resync,omitempty"`
	UdpPackets       *uint32  `protobuf:"varint,6,opt,name=udp_packets" json:"udp_packets,omitempty"`
	TcpPackets       *uint32  `protobuf:"varint,7,opt,name=tcp_packets" json:"tcp_packets,omitempty"`
	UdpPingAvg       *float32 `protobuf:"fixed32,8,opt,name=udp_ping_avg" json:"udp_ping_avg,omitempty"`
	UdpPingVar       *float32 `protobuf:"fixed32,9,opt,name=udp_ping_var" json:"udp_ping_var,omitempty"`
	TcpPingAvg       *float32 `protobuf:"fixed32,10,opt,name=tcp_ping_avg" json:"tcp_ping_avg,omitempty"`
	TcpPingVar       *float32 `protobuf:"fixed32,11,opt,name=tcp_ping_var" json:"tcp_ping_var,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Ping) Reset()         { *this = Ping{} }
func (this *Ping) String() string { return proto.CompactTextString(this) }

type Reject struct {
	Type             *Reject_RejectType `protobuf:"varint,1,opt,name=type,enum=mumbleproto.Reject_RejectType" json:"type,omitempty"`
	Reason           *string            `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte             `json:",omitempty"`
}

func (this *Reject) Reset()         { *this = Reject{} }
func (this *Reject) String() string { return proto.CompactTextString(this) }

type ServerConfig struct {
	MaxBandwidth       *uint32 `protobuf:"varint,1,opt,name=max_bandwidth" json:"max_bandwidth,omitempty"`
	WelcomeText        *string `protobuf:"bytes,2,opt,name=welcome_text" json:"welcome_text,omitempty"`
	AllowHtml          *bool   `protobuf:"varint,3,opt,name=allow_html" json:"allow_html,omitempty"`
	MessageLength      *uint32 `protobuf:"varint,4,opt,name=message_length" json:"message_length,omitempty"`
	ImageMessageLength *uint32 `protobuf:"varint,5,opt,name=image_message_length" json:"image_message_length,omitempty"`
	XXX_unrecognized   []byte  `json:",omitempty"`
}

func (this *ServerConfig) Reset()         { *this = ServerConfig{} }
func (this *ServerConfig) String() string { return proto.CompactTextString(this) }

type ServerSync struct {
	Session          *uint32 `protobuf:"varint,1,opt,name=session" json:"session,omitempty"`
	MaxBandwidth     *uint32 `protobuf:"varint,2,opt,name=max_bandwidth" json:"max_bandwidth,omitempty"`
	WelcomeText      *string `protobuf:"bytes,3,opt,name=welcome_text" json:"welcome_text,omitempty"`
	Permissions      *uint64 `protobuf:"varint,4,opt,name=permissions" json:"permissions,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ServerSync) Reset()         { *this = ServerSync{} }
func (this *ServerSync) String() string { return proto.CompactTextString(this) }

type ChannelRemove struct {
	ChannelId        *uint32 `protobuf:"varint,1,req,name=channel_id" json:"channel_id,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ChannelRemove) Reset()         { *this = ChannelRemove{} }
func (this *ChannelRemove) String() string { return proto.CompactTextString(this) }

type ChannelState struct {
	ChannelId        *uint32  `protobuf:"varint,1,opt,name=channel_id" json:"channel_id,omitempty"`
	Parent           *uint32  `protobuf:"varint,2,opt,name=parent" json:"parent,omitempty"`
	Name             *string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Links            []uint32 `protobuf:"varint,4,rep,name=links" json:"links,omitempty"`
	Description      *string  `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	LinksAdd         []uint32 `protobuf:"varint,6,rep,name=links_add" json:"links_add,omitempty"`
	LinksRemove      []uint32 `protobuf:"varint,7,rep,name=links_remove" json:"links_remove,omitempty"`
	Temporary        *bool    `protobuf:"varint,8,opt,name=temporary,def=0" json:"temporary,omitempty"`
	Position         *int32   `protobuf:"varint,9,opt,name=position,def=0" json:"position,omitempty"`
	DescriptionHash  []byte   `protobuf:"bytes,10,opt,name=description_hash" json:"description_hash,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *ChannelState) Reset()         { *this = ChannelState{} }
func (this *ChannelState) String() string { return proto.CompactTextString(this) }

const Default_ChannelState_Temporary bool = false
const Default_ChannelState_Position int32 = 0

type UserRemove struct {
	Session          *uint32 `protobuf:"varint,1,req,name=session" json:"session,omitempty"`
	Actor            *uint32 `protobuf:"varint,2,opt,name=actor" json:"actor,omitempty"`
	Reason           *string `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	Ban              *bool   `protobuf:"varint,4,opt,name=ban" json:"ban,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserRemove) Reset()         { *this = UserRemove{} }
func (this *UserRemove) String() string { return proto.CompactTextString(this) }

type UserState struct {
	Session          *uint32 `protobuf:"varint,1,opt,name=session" json:"session,omitempty"`
	Actor            *uint32 `protobuf:"varint,2,opt,name=actor" json:"actor,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	UserId           *uint32 `protobuf:"varint,4,opt,name=user_id" json:"user_id,omitempty"`
	ChannelId        *uint32 `protobuf:"varint,5,opt,name=channel_id" json:"channel_id,omitempty"`
	Mute             *bool   `protobuf:"varint,6,opt,name=mute" json:"mute,omitempty"`
	Deaf             *bool   `protobuf:"varint,7,opt,name=deaf" json:"deaf,omitempty"`
	Suppress         *bool   `protobuf:"varint,8,opt,name=suppress" json:"suppress,omitempty"`
	SelfMute         *bool   `protobuf:"varint,9,opt,name=self_mute" json:"self_mute,omitempty"`
	SelfDeaf         *bool   `protobuf:"varint,10,opt,name=self_deaf" json:"self_deaf,omitempty"`
	Texture          []byte  `protobuf:"bytes,11,opt,name=texture" json:"texture,omitempty"`
	PluginContext    []byte  `protobuf:"bytes,12,opt,name=plugin_context" json:"plugin_context,omitempty"`
	PluginIdentity   *string `protobuf:"bytes,13,opt,name=plugin_identity" json:"plugin_identity,omitempty"`
	Comment          *string `protobuf:"bytes,14,opt,name=comment" json:"comment,omitempty"`
	Hash             *string `protobuf:"bytes,15,opt,name=hash" json:"hash,omitempty"`
	CommentHash      []byte  `protobuf:"bytes,16,opt,name=comment_hash" json:"comment_hash,omitempty"`
	TextureHash      []byte  `protobuf:"bytes,17,opt,name=texture_hash" json:"texture_hash,omitempty"`
	PrioritySpeaker  *bool   `protobuf:"varint,18,opt,name=priority_speaker" json:"priority_speaker,omitempty"`
	Recording        *bool   `protobuf:"varint,19,opt,name=recording" json:"recording,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserState) Reset()         { *this = UserState{} }
func (this *UserState) String() string { return proto.CompactTextString(this) }

type BanList struct {
	Bans             []*BanList_BanEntry `protobuf:"bytes,1,rep,name=bans" json:"bans,omitempty"`
	Query            *bool               `protobuf:"varint,2,opt,name=query,def=0" json:"query,omitempty"`
	XXX_unrecognized []byte              `json:",omitempty"`
}

func (this *BanList) Reset()         { *this = BanList{} }
func (this *BanList) String() string { return proto.CompactTextString(this) }

const Default_BanList_Query bool = false

type BanList_BanEntry struct {
	Address          []byte  `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Mask             *uint32 `protobuf:"varint,2,req,name=mask" json:"mask,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Hash             *string `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	Reason           *string `protobuf:"bytes,5,opt,name=reason" json:"reason,omitempty"`
	Start            *string `protobuf:"bytes,6,opt,name=start" json:"start,omitempty"`
	Duration         *uint32 `protobuf:"varint,7,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *BanList_BanEntry) Reset()         { *this = BanList_BanEntry{} }
func (this *BanList_BanEntry) String() string { return proto.CompactTextString(this) }

type TextMessage struct {
	Actor            *uint32  `protobuf:"varint,1,opt,name=actor" json:"actor,omitempty"`
	Session          []uint32 `protobuf:"varint,2,rep,name=session" json:"session,omitempty"`
	ChannelId        []uint32 `protobuf:"varint,3,rep,name=channel_id" json:"channel_id,omitempty"`
	TreeId           []uint32 `protobuf:"varint,4,rep,name=tree_id" json:"tree_id,omitempty"`
	Message          *string  `protobuf:"bytes,5,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *TextMessage) Reset()         { *this = TextMessage{} }
func (this *TextMessage) String() string { return proto.CompactTextString(this) }

type PermissionDenied struct {
	Permission       *uint32                    `protobuf:"varint,1,opt,name=permission" json:"permission,omitempty"`
	ChannelId        *uint32                    `protobuf:"varint,2,opt,name=channel_id" json:"channel_id,omitempty"`
	Session          *uint32                    `protobuf:"varint,3,opt,name=session" json:"session,omitempty"`
	Reason           *string                    `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
	Type             *PermissionDenied_DenyType `protobuf:"varint,5,opt,name=type,enum=mumbleproto.PermissionDenied_DenyType" json:"type,omitempty"`
	Name             *string                    `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte                     `json:",omitempty"`
}

func (this *PermissionDenied) Reset()         { *this = PermissionDenied{} }
func (this *PermissionDenied) String() string { return proto.CompactTextString(this) }

type ACL struct {
	ChannelId        *uint32          `protobuf:"varint,1,req,name=channel_id" json:"channel_id,omitempty"`
	InheritAcls      *bool            `protobuf:"varint,2,opt,name=inherit_acls,def=1" json:"inherit_acls,omitempty"`
	Groups           []*ACL_ChanGroup `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	Acls             []*ACL_ChanACL   `protobuf:"bytes,4,rep,name=acls" json:"acls,omitempty"`
	Query            *bool            `protobuf:"varint,5,opt,name=query,def=0" json:"query,omitempty"`
	XXX_unrecognized []byte           `json:",omitempty"`
}

func (this *ACL) Reset()         { *this = ACL{} }
func (this *ACL) String() string { return proto.CompactTextString(this) }

const Default_ACL_InheritAcls bool = true
const Default_ACL_Query bool = false

type ACL_ChanGroup struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Inherited        *bool    `protobuf:"varint,2,opt,name=inherited,def=1" json:"inherited,omitempty"`
	Inherit          *bool    `protobuf:"varint,3,opt,name=inherit,def=1" json:"inherit,omitempty"`
	Inheritable      *bool    `protobuf:"varint,4,opt,name=inheritable,def=1" json:"inheritable,omitempty"`
	Add              []uint32 `protobuf:"varint,5,rep,name=add" json:"add,omitempty"`
	Remove           []uint32 `protobuf:"varint,6,rep,name=remove" json:"remove,omitempty"`
	InheritedMembers []uint32 `protobuf:"varint,7,rep,name=inherited_members" json:"inherited_members,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *ACL_ChanGroup) Reset()         { *this = ACL_ChanGroup{} }
func (this *ACL_ChanGroup) String() string { return proto.CompactTextString(this) }

const Default_ACL_ChanGroup_Inherited bool = true
const Default_ACL_ChanGroup_Inherit bool = true
const Default_ACL_ChanGroup_Inheritable bool = true

type ACL_ChanACL struct {
	ApplyHere        *bool   `protobuf:"varint,1,opt,name=apply_here,def=1" json:"apply_here,omitempty"`
	ApplySubs        *bool   `protobuf:"varint,2,opt,name=apply_subs,def=1" json:"apply_subs,omitempty"`
	Inherited        *bool   `protobuf:"varint,3,opt,name=inherited,def=1" json:"inherited,omitempty"`
	UserId           *uint32 `protobuf:"varint,4,opt,name=user_id" json:"user_id,omitempty"`
	Group            *string `protobuf:"bytes,5,opt,name=group" json:"group,omitempty"`
	Grant            *uint32 `protobuf:"varint,6,opt,name=grant" json:"grant,omitempty"`
	Deny             *uint32 `protobuf:"varint,7,opt,name=deny" json:"deny,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ACL_ChanACL) Reset()         { *this = ACL_ChanACL{} }
func (this *ACL_ChanACL) String() string { return proto.CompactTextString(this) }

const Default_ACL_ChanACL_ApplyHere bool = true
const Default_ACL_ChanACL_ApplySubs bool = true
const Default_ACL_ChanACL_Inherited bool = true

type QueryUsers struct {
	Ids              []uint32 `protobuf:"varint,1,rep,name=ids" json:"ids,omitempty"`
	Names            []string `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *QueryUsers) Reset()         { *this = QueryUsers{} }
func (this *QueryUsers) String() string { return proto.CompactTextString(this) }

type CryptSetup struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	ClientNonce      []byte `protobuf:"bytes,2,opt,name=client_nonce" json:"client_nonce,omitempty"`
	ServerNonce      []byte `protobuf:"bytes,3,opt,name=server_nonce" json:"server_nonce,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *CryptSetup) Reset()         { *this = CryptSetup{} }
func (this *CryptSetup) String() string { return proto.CompactTextString(this) }

type ContextActionModify struct {
	Action           *string                        `protobuf:"bytes,1,req,name=action" json:"action,omitempty"`
	Text             *string                        `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Context          *uint32                        `protobuf:"varint,3,opt,name=context" json:"context,omitempty"`
	Operation        *ContextActionModify_Operation `protobuf:"varint,4,opt,name=operation,enum=mumbleproto.ContextActionModify_Operation" json:"operation,omitempty"`
	XXX_unrecognized []byte                         `json:",omitempty"`
}

func (this *ContextActionModify) Reset()         { *this = ContextActionModify{} }
func (this *ContextActionModify) String() string { return proto.CompactTextString(this) }

type ContextAction struct {
	Session          *uint32 `protobuf:"varint,1,opt,name=session" json:"session,omitempty"`
	ChannelId        *uint32 `protobuf:"varint,2,opt,name=channel_id" json:"channel_id,omitempty"`
	Action           *string `protobuf:"bytes,3,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *ContextAction) Reset()         { *this = ContextAction{} }
func (this *ContextAction) String() string { return proto.CompactTextString(this) }

type UserList struct {
	Users            []*UserList_User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte           `json:",omitempty"`
}

func (this *UserList) Reset()         { *this = UserList{} }
func (this *UserList) String() string { return proto.CompactTextString(this) }

type UserList_User struct {
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserList_User) Reset()         { *this = UserList_User{} }
func (this *UserList_User) String() string { return proto.CompactTextString(this) }

type VoiceTarget struct {
	Id               *uint32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Targets          []*VoiceTarget_Target `protobuf:"bytes,2,rep,name=targets" json:"targets,omitempty"`
	XXX_unrecognized []byte                `json:",omitempty"`
}

func (this *VoiceTarget) Reset()         { *this = VoiceTarget{} }
func (this *VoiceTarget) String() string { return proto.CompactTextString(this) }

type VoiceTarget_Target struct {
	Session          []uint32 `protobuf:"varint,1,rep,name=session" json:"session,omitempty"`
	ChannelId        *uint32  `protobuf:"varint,2,opt,name=channel_id" json:"channel_id,omitempty"`
	Group            *string  `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Links            *bool    `protobuf:"varint,4,opt,name=links,def=0" json:"links,omitempty"`
	Children         *bool    `protobuf:"varint,5,opt,name=children,def=0" json:"children,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *VoiceTarget_Target) Reset()         { *this = VoiceTarget_Target{} }
func (this *VoiceTarget_Target) String() string { return proto.CompactTextString(this) }

const Default_VoiceTarget_Target_Links bool = false
const Default_VoiceTarget_Target_Children bool = false

type PermissionQuery struct {
	ChannelId        *uint32 `protobuf:"varint,1,opt,name=channel_id" json:"channel_id,omitempty"`
	Permissions      *uint32 `protobuf:"varint,2,opt,name=permissions" json:"permissions,omitempty"`
	Flush            *bool   `protobuf:"varint,3,opt,name=flush,def=0" json:"flush,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *PermissionQuery) Reset()         { *this = PermissionQuery{} }
func (this *PermissionQuery) String() string { return proto.CompactTextString(this) }

const Default_PermissionQuery_Flush bool = false

type CodecVersion struct {
	Alpha            *int32 `protobuf:"varint,1,req,name=alpha" json:"alpha,omitempty"`
	Beta             *int32 `protobuf:"varint,2,req,name=beta" json:"beta,omitempty"`
	PreferAlpha      *bool  `protobuf:"varint,3,req,name=prefer_alpha,def=1" json:"prefer_alpha,omitempty"`
	Opus             *bool  `protobuf:"varint,4,opt,name=opus,def=0" json:"opus,omitempty"`
	XXX_unrecognized []byte `json:",omitempty"`
}

func (this *CodecVersion) Reset()         { *this = CodecVersion{} }
func (this *CodecVersion) String() string { return proto.CompactTextString(this) }

const Default_CodecVersion_PreferAlpha bool = true
const Default_CodecVersion_Opus bool = false

type UserStats struct {
	Session           *uint32          `protobuf:"varint,1,opt,name=session" json:"session,omitempty"`
	StatsOnly         *bool            `protobuf:"varint,2,opt,name=stats_only,def=0" json:"stats_only,omitempty"`
	Certificates      [][]byte         `protobuf:"bytes,3,rep,name=certificates" json:"certificates,omitempty"`
	FromClient        *UserStats_Stats `protobuf:"bytes,4,opt,name=from_client" json:"from_client,omitempty"`
	FromServer        *UserStats_Stats `protobuf:"bytes,5,opt,name=from_server" json:"from_server,omitempty"`
	UdpPackets        *uint32          `protobuf:"varint,6,opt,name=udp_packets" json:"udp_packets,omitempty"`
	TcpPackets        *uint32          `protobuf:"varint,7,opt,name=tcp_packets" json:"tcp_packets,omitempty"`
	UdpPingAvg        *float32         `protobuf:"fixed32,8,opt,name=udp_ping_avg" json:"udp_ping_avg,omitempty"`
	UdpPingVar        *float32         `protobuf:"fixed32,9,opt,name=udp_ping_var" json:"udp_ping_var,omitempty"`
	TcpPingAvg        *float32         `protobuf:"fixed32,10,opt,name=tcp_ping_avg" json:"tcp_ping_avg,omitempty"`
	TcpPingVar        *float32         `protobuf:"fixed32,11,opt,name=tcp_ping_var" json:"tcp_ping_var,omitempty"`
	Version           *Version         `protobuf:"bytes,12,opt,name=version" json:"version,omitempty"`
	CeltVersions      []int32          `protobuf:"varint,13,rep,name=celt_versions" json:"celt_versions,omitempty"`
	Address           []byte           `protobuf:"bytes,14,opt,name=address" json:"address,omitempty"`
	Bandwidth         *uint32          `protobuf:"varint,15,opt,name=bandwidth" json:"bandwidth,omitempty"`
	Onlinesecs        *uint32          `protobuf:"varint,16,opt,name=onlinesecs" json:"onlinesecs,omitempty"`
	Idlesecs          *uint32          `protobuf:"varint,17,opt,name=idlesecs" json:"idlesecs,omitempty"`
	StrongCertificate *bool            `protobuf:"varint,18,opt,name=strong_certificate,def=0" json:"strong_certificate,omitempty"`
	Opus              *bool            `protobuf:"varint,19,opt,name=opus,def=0" json:"opus,omitempty"`
	XXX_unrecognized  []byte           `json:",omitempty"`
}

func (this *UserStats) Reset()         { *this = UserStats{} }
func (this *UserStats) String() string { return proto.CompactTextString(this) }

const Default_UserStats_StatsOnly bool = false
const Default_UserStats_StrongCertificate bool = false
const Default_UserStats_Opus bool = false

type UserStats_Stats struct {
	Good             *uint32 `protobuf:"varint,1,opt,name=good" json:"good,omitempty"`
	Late             *uint32 `protobuf:"varint,2,opt,name=late" json:"late,omitempty"`
	Lost             *uint32 `protobuf:"varint,3,opt,name=lost" json:"lost,omitempty"`
	Resync           *uint32 `protobuf:"varint,4,opt,name=resync" json:"resync,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *UserStats_Stats) Reset()         { *this = UserStats_Stats{} }
func (this *UserStats_Stats) String() string { return proto.CompactTextString(this) }

type SuggestConfig struct {
	Version          *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Positional       *bool   `protobuf:"varint,2,opt,name=positional" json:"positional,omitempty"`
	PushToTalk       *bool   `protobuf:"varint,3,opt,name=push_to_talk" json:"push_to_talk,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *SuggestConfig) Reset()         { *this = SuggestConfig{} }
func (this *SuggestConfig) String() string { return proto.CompactTextString(this) }

type RequestBlob struct {
	SessionTexture     []uint32 `protobuf:"varint,1,rep,name=session_texture" json:"session_texture,omitempty"`
	SessionComment     []uint32 `protobuf:"varint,2,rep,name=session_comment" json:"session_comment,omitempty"`
	ChannelDescription []uint32 `protobuf:"varint,3,rep,name=channel_description" json:"channel_description,omitempty"`
	XXX_unrecognized   []byte   `json:",omitempty"`
}

func (this *RequestBlob) Reset()         { *this = RequestBlob{} }
func (this *RequestBlob) String() string { return proto.CompactTextString(this) }

func init() {
	proto.RegisterEnum("mumbleproto.Reject_RejectType", Reject_RejectType_name, Reject_RejectType_value)
	proto.RegisterEnum("mumbleproto.PermissionDenied_DenyType", PermissionDenied_DenyType_name, PermissionDenied_DenyType_value)
	proto.RegisterEnum("mumbleproto.ContextActionModify_Context", ContextActionModify_Context_name, ContextActionModify_Context_value)
	proto.RegisterEnum("mumbleproto.ContextActionModify_Operation", ContextActionModify_Operation_name, ContextActionModify_Operation_value)
}
